// One-time setup: creates the Ed25519 key pair used to sign license keys.
//   npm run license:keygen
// Writes the private key to ~/.salla-excel-merger/license-private-key.pem
// (or $LICENSE_PRIVATE_KEY_PATH) and the public key into src/main/license/publicKey.ts.

import { generateKeyPairSync } from 'crypto'
import { existsSync, mkdirSync, writeFileSync } from 'fs'
import { dirname } from 'path'
import { publicKeyToBase64 } from '../../src/main/license/core'
import { PRIVATE_KEY_PATH, PUBLIC_KEY_SOURCE } from './paths'

if (existsSync(PRIVATE_KEY_PATH)) {
  console.error(`A private key already exists at:\n  ${PRIVATE_KEY_PATH}\n`)
  console.error(
    'Refusing to overwrite it: a new key pair would invalidate every license already issued.'
  )
  process.exit(1)
}

const { publicKey, privateKey } = generateKeyPairSync('ed25519')

mkdirSync(dirname(PRIVATE_KEY_PATH), { recursive: true })
writeFileSync(PRIVATE_KEY_PATH, privateKey.export({ format: 'pem', type: 'pkcs8' }), {
  mode: 0o600
})

writeFileSync(
  PUBLIC_KEY_SOURCE,
  `// Ed25519 public key (SPKI DER, base64) used to verify license keys.
// Generated by \`npm run license:keygen\` — do not edit by hand.
// An empty value means no key pair has been generated yet; the release
// workflow refuses to build in that state (\`npm run license:check\`).
export const LICENSE_PUBLIC_KEY = '${publicKeyToBase64(publicKey)}'
`
)

console.log(`Private key written to:\n  ${PRIVATE_KEY_PATH}\n`)
console.log(`Public key written to:\n  ${PUBLIC_KEY_SOURCE}\n`)
console.log('Next steps:')
console.log(
  '  1. BACK UP the private key file somewhere safe (e.g. a password manager or USB drive).'
)
console.log('     If you lose it you cannot issue new keys; if it leaks anyone can.')
console.log('     Never commit it or send it to anyone.')
console.log('  2. Commit src/main/license/publicKey.ts and release a new version.')
