// Ed25519 public key (SPKI DER, base64) used to verify license keys.
// Generated by `npm run license:keygen` — do not edit by hand.
// An empty value means no key pair has been generated yet; the release
// workflow refuses to build in that state (`npm run license:check`).
export const LICENSE_PUBLIC_KEY = 'MCowBQYDK2VwAyEA0ZOOx5HMfFHKfniL4cfhvR2/kFEowXqXO79iNLncKow='
